### ISSUE TITLE
keine Unterscheidung der Verbindungsart bei Dresdner Clients

### ISSUE THREAD

**Issue by mokkin** [freifunkstuff/meshviewer-ffle#2]
Bei den neuen Knoten mit Dresdner Firmware scheint die Darstellung der Clients nicht mehr zu funktionieren, also ob sie im 2,4GHz, 5GHz oder auf sonstige Art verbunden sind.

**Comment by micw** [comment]
Das liegt daran, dass die Info nicht mit im JSON steht. Ich werde mit DD eine API für die Knoten-Daten abstimmen, dann haben wir alles, was wir benötigen.

**Comment by micw** [comment]
Ist umgesetzt in https://github.com/freifunkstuff/meshviewer + mapcollector
